POST http://localhost:3000/add
Content-Type: application/json

{
    "username": "secondtry",
    "password": "krishna"
}

###
GET http://localhost:3000/data

###
GET http://localhost:3000/info/66feda01bce9ea31ab4699fa
